### ISSUE TITLE
Create a docker image with the contents of puppet-runtime artifact

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/devx#12]
1. Use existing puppet-runtime configs, but extract what we need
 1. Will have ruby and the gems for that specific puppet version
 1. Install pdk gem

**Comment by jpogran** [comment]
1. Create a docker image with the contents of puppet-runtime artifact
    1. Use existing puppet-runtime configs, but extract what we need
    1. Will have ruby and the gems for that specific puppet version
    1. Install pdk gem  
1. Show something using that docker image as an entry point
1. Review performance of this solution

**Comment by da-ar** [comment]
I hadto go further up the build process to get the parts i needed. Using a debian package of the PDK, I extracted the contents to an image and removed the parts I beleived were excess. 
This process was repeated to create images for puppet 5, 6 & 7.
