### ISSUE TITLE
Consolidate all open issues related to validate feature

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/devx#14]

**Comment by jpogran** [comment]
- [ ] All JIRA moved to github issues or discussions
  - [ ] Close jira when github issue has all detail
- [ ] PDK github issues groomed
  - [ ] Determine if already fixed or valid
  - [ ] Make list of important to review adding to PDK Release Project/Epic
- [ ] PDK-planning RFCs related to validate moved to discussion
  - [ ] These are the checked in RFC leftover from the move to discussions

**Comment by sanfrancrisko** [comment]
## JIRA Migrations to Discussions
- [PDK-958](https://tickets.puppetlabs.com/browse/PDK-958) -> [pdk/discussions/1051](https://github.com/puppetlabs/pdk/discussions/1051)
- [PDK-679](https://tickets.puppetlabs.com/browse/PDK-958) -> [pdk/discussions/1052](https://github.com/puppetlabs/pdk/discussions/1052)
- [PDK-826](https://tickets.puppetlabs.com/browse/PDK-958) -> [pdk/discussions/1055](https://github.com/puppetlabs/pdk/discussions/1055)
- [PDK-677](https://tickets.puppetlabs.com/browse/PDK-677) -> [pdk/discussions/1056](https://github.com/puppetlabs/pdk/discussions/1056)
- [PDK-1316](https://tickets.puppetlabs.com/browse/PDK-677) -> [pdk/discussions/1057](https://github.com/puppetlabs/pdk/discussions/1057)
- [PDK-564](https://tickets.puppetlabs.com/browse/PDK-564) -> [pdk/discussions/1058](https://github.com/puppetlabs/pdk/discussions/1058)
- [PDK-742](https://tickets.puppetlabs.com/browse/PDK-742) -> [pdk/discussions/1060](https://github.com/puppetlabs/pdk/discussions/1060)
- [PDK-711](https://tickets.puppetlabs.com/browse/PDK-711) -> [pdk/discussions/1062](https://github.com/puppetlabs/pdk/discussions/1062)
- [PDK-501](https://tickets.puppetlabs.com/browse/PDK-501) -> [pdk/discussions/1062](https://github.com/puppetlabs/pdk/discussions/1064) 
- [PDK-1680](https://tickets.puppetlabs.com/browse/PDK-1680) -> [pdk/discussions/1065](https://github.com/puppetlabs/pdk/discussions/1065)
- [PDK-663](https://tickets.puppetlabs.com/browse/PDK-663) [PDK-1395](https://tickets.puppetlabs.com/browse/PDK-1395)  -> [pdk/discussions/1066](https://github.com/puppetlabs/pdk/discussions/1066)
